- id: '1744896421298'
  alias: Rodret to Tradfri
  description: ''
  use_blueprint:
    path: damru/ikea_E1743-E2201-E2213_ZHA-Z2M_control-light.yaml
    input:
      light: light.cuisine_plans_de_travail
      remote_devices:
      - df5b9b63c997a2417895397f2d10f3bf
- id: '1744908930050'
  alias: 'Frontend: turn on dark mode'
  triggers:
  - trigger: time
    at: '20:00:00'
  - trigger: sun
    event: sunset
  conditions:
  - condition: template
    value_template: '{{ is_state(''input_boolean.dark_mode'', ''off'') }}'
  actions:
  - entity_id: input_boolean.dark_mode
    action: input_boolean.turn_on
- id: '1744909014251'
  alias: 'Frontend: turn on light mode'
  triggers:
  - trigger: time
    at: 06:00
  - trigger: sun
    event: sunrise
  conditions:
  - '{{ is_state(''input_boolean.dark_mode'', ''on'') }}'
  actions:
  - entity_id: input_boolean.dark_mode
    action: input_boolean.turn_off
- id: '1744909161819'
  alias: 'Frontend: change theme'
  description: ''
  triggers:
  - trigger: state
    entity_id: input_select.theme
  - trigger: state
    entity_id: input_boolean.dark_mode
  - trigger: state
    entity_id: input_boolean.theme_alternative
  - trigger: homeassistant
    event: start
  actions:
  - action: frontend.set_theme
    data:
      name: '{% set which = "dark" if is_state("input_boolean.dark_mode", "on") else
        "light" -%} {% set name = states("input_select.theme") -%} {% set suffix =
        "-alternative" if is_state("input_boolean.theme_alternative", "on") else ""
        -%} ios-{{ which }}-mode-{{ name }}{{ suffix }}

        '
