- id: '1769005223143'
  alias: Sonoff Zigbee Button
  description: ''
  use_blueprint:
    path: sonoff/blueprint-zha-snzb-01p.yaml
    input:
      remote: 80774417407683d5c5d59e83bcefeea7

      single_press:
        - choose:
            - conditions:
                - condition: state
                  entity_id: input_boolean.movie_mode_active
                  state: "off"
              sequence:
                - action: script.audio_movie_mode_on
          default:
            - action: script.audio_movie_mode_off

      double_press:
        - choose:
            - conditions:
                - condition: state
                  entity_id: input_boolean.music_mode_active
                  state: "off"
              sequence:
                - action: script.audio_music_mode_on
          default:
            - action: script.audio_music_mode_off

      hold:
        - action: script.audio_goodnight
- id: '1769007195923'
  alias: "Presence & Access: Closet light"
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.ewelink_snzb_04p
      light_switch:
        entity_id: light.tz3210_cieijuw1_ts0505b_2
      time_delay: 0
      include_light_control:
      - use_brightness
      motion_bypass_lights_on: []
      include_bypass: []
      motion_bypass_lights_off: []
