# Core Configuration
homeassistant: !include includes/homeassistant.yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes
http: !include includes/http.yaml

# Managed via UI
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Others
zone: !include includes/zones.yaml
# automation manual: !include automations.yaml
light: !include includes/lights.yaml
recorder: !include includes/recorder.yaml

# Custom components
template: !include includes/templates.yaml

sensor:
  - platform: rest
    name: "Sensor Light Blueprint Gist Version Number"
    icon: mdi:cloud-tags
    resource: "https://gist.githubusercontent.com/Blackshome/6edfec0ff6a25c5da0d07b88dc908238/raw/sensor-light.yaml"
    method: GET
    headers:
      accept: "text/plain"
    value_template: >
      {% set match = value | regex_findall('\\*\\*Version:\\s*([0-9.]+)\\*\\*') %}
      {{ match[0] if match else 'unknown' }}
    scan_interval: 86400
  - platform: rest
    name: "Sensor Light Add On Blueprint Gist Version Number"
    icon: mdi:cloud-tags
    resource: "https://gist.github.com/Blackshome/85d6e7dbfa3390afbcf3e801b8be6294/raw/sensor-light-add-on.yaml"
    method: GET
    headers:
      accept: "text/plain"
    value_template: >
      {% set match = value | regex_findall('\\*\\*Version:\\s*([0-9.]+)\\*\\*') %}
      {{ match[0] if match else 'unknown' }}
    scan_interval: 86400
  - platform: rest
    name: "Holiday & Away Lighting Blueprint Gist Version Number"
    icon: mdi:cloud-tags
    resource: "https://gist.github.com/Blackshome/0a34870755762bcb9fab159d5b94fd25/raw/holiday-away-lighting.yaml"
    method: GET
    headers:
      accept: "text/plain"
    value_template: >
      {% set match = value | regex_findall('\\*\\*Version:\\s*([0-9.]+)\\*\\*') %}
      {{ match[0] if match else 'unknown' }}
    scan_interval: 86400
  - platform: rest
    name: "Low Battery Blueprint Gist Version Number"
    icon: mdi:cloud-tags
    resource: "https://gist.github.com/Blackshome/4010fb83bb8c19b5fa1425526c6ff0e2/raw/low-battery-notifications-and-actions.yaml"
    method: GET
    headers:
      accept: "text/plain"
    value_template: >
      {% set match = value | regex_findall('\\*\\*Version:\\s*([0-9.]+)\\*\\*') %}
      {{ match[0] if match else 'unknown' }}
    scan_interval: 86400
  - platform: rest
    name: "Appliance Notification Blueprint Gist Version Number"
    icon: mdi:cloud-tags
    resource: "https://gist.github.com/Blackshome/42586b567d243d432887cadf54e18906/raw/appliance-notifications.yaml"
    method: GET
    headers:
      accept: "text/plain"
    value_template: >
      {% set match = value | regex_findall('\\*\\*Version:\\s*([0-9.]+)\\*\\*') %}
      {{ match[0] if match else 'unknown' }}
    scan_interval: 86400
  - platform: rest
    name: "Blueprint Update Notifications Blueprint Gist Version Number"
    icon: mdi:cloud-tags
    resource: "https://gist.github.com/Blackshome/ede9cf745f3b86ff8576c21b6ca1509a/raw/blueprint-update-notifications.yaml"
    method: GET
    headers:
      accept: "text/plain"
    value_template: >
      {% set match = value | regex_findall('\\*\\*Version:\\s*([0-9.]+)\\*\\*') %}
      {{ match[0] if match else 'unknown' }}
    scan_interval: 86400
  - platform: rest
    name: "Closet, Pantry, and Cupboard Lighting Blueprint Gist Version Number"
    icon: mdi:cloud-tags
    resource: "https://gist.github.com/Blackshome/5aac0fe94d23a71154aee5ba8d1375bc/raw/closet-pantry-cupboard-lighting.yaml"
    method: GET
    headers:
      accept: "text/plain"
    value_template: >
      {% set match = value | regex_findall('\\*\\*Version:\\s*([0-9.]+)\\*\\*') %}
      {{ match[0] if match else 'unknown' }}
    scan_interval: 86400
  - platform: rest
    name: "Zone Presence of People & Devices Blueprint Gist Version Number"
    icon: mdi:cloud-tags
    resource: "https://gist.github.com/Blackshome/798cd918c0d078cbc901d5894a0aa6b1/raw/zone-presence-people-device.yaml"
    method: GET
    headers:
      accept: "text/plain"
    value_template: >
      {% set match = value | regex_findall('\\*\\*Version:\\s*([0-9.]+)\\*\\*') %}
      {{ match[0] if match else 'unknown' }}
    scan_interval: 86400
  - platform: rest
    name: "State Notifications & Actions Blueprint Gist Version Number"
    icon: mdi:cloud-tags
    resource: "https://gist.github.com/Blackshome/06f6f28e76299267b813dac48608f549/raw/state-notifications-and-actions.yaml"
    method: GET
    headers:
      accept: "text/plain"
    value_template: >
      {% set match = value | regex_findall('\\*\\*Version:\\s*([0-9.]+)\\*\\*') %}
      {{ match[0] if match else 'unknown' }}
    scan_interval: 86400

command_line:
  - sensor:
      name: "Sensor Light Blueprint Local Version Number"
      icon: mdi:code-not-equal-variant
      command: "grep -oE '[*][*]Version: [0-9.]+' /config/blueprints/automation/Blackshome/sensor-light.yaml | grep -oE '[0-9.]+'"
      scan_interval: 86400
  - sensor:
      name: "Sensor Light Add On Blueprint Local Version Number"
      icon: mdi:code-not-equal-variant
      command: "grep -oE '[*][*]Version: [0-9.]+' /config/blueprints/automation/Blackshome/sensor-light-add-on.yaml | grep -oE '[0-9.]+'"
      scan_interval: 86400
  - sensor:
      name: "Holiday & Away Lighting Blueprint Local Version Number"
      icon: mdi:code-not-equal-variant
      command: "grep -oE '[*][*]Version: [0-9.]+' /config/blueprints/automation/Blackshome/holiday-away-lighting.yaml | grep -oE '[0-9.]+'"
      scan_interval: 86400
  - sensor:
      name: "Low Battery Blueprint Local Version Number"
      icon: mdi:code-not-equal-variant
      command: "grep -oE '[*][*]Version: [0-9.]+' /config/blueprints/automation/Blackshome/low-battery-notifications-and-actions.yaml | grep -oE '[0-9.]+'"
      scan_interval: 86400
  - sensor:
      name: "Apliance Notification Blueprint Local Version Number"
      icon: mdi:code-not-equal-variant
      command: "grep -oE '[*][*]Version: [0-9.]+' /config/blueprints/automation/Blackshome/appliance-notifications.yaml | grep -oE '[0-9.]+'"
      scan_interval: 86400
  - sensor:
      name: "Blueprint Update Notifications Blueprint Local Version Number"
      icon: mdi:code-not-equal-variant
      command: "grep -oE '[*][*]Version: [0-9.]+' /config/blueprints/automation/Blackshome/blueprint-update-notifications.yaml | grep -oE '[0-9.]+'"
      scan_interval: 86400
  - sensor:
      name: "Closet, Pantry, and Cupboard Lighting Blueprint Local Version Number"
      icon: mdi:code-not-equal-variant
      command: "grep -oE '[*][*]Version: [0-9.]+' /config/blueprints/automation/Blackshome/closet-pantry-cupboard-lighting.yaml | grep -oE '[0-9.]+'"
      scan_interval: 86400
  - sensor:
      name: "Zone Presence of People & Devices Blueprint Local Version Number"
      icon: mdi:code-not-equal-variant
      command: "grep -oE '[*][*]Version: [0-9.]+' /config/blueprints/automation/Blackshome/zone-presence-people-device.yaml | grep -oE '[0-9.]+'"
      scan_interval: 86400
  - sensor:
      name: "State Notifications & Actions Blueprint Local Version Number"
      icon: mdi:code-not-equal-variant
      command: "grep -oE '[*][*]Version: [0-9.]+' /config/blueprints/automation/Blackshome/state-notifications-and-actions.yaml | grep -oE '[0-9.]+'"
      scan_interval: 86400