# Core Configuration
homeassistant: !include includes/homeassistant.yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes
http: !include includes/http.yaml
lovelace: !include ui-lovelace.yaml

# Inputs
input_boolean: !include includes/input_booleans.yaml
input_datetime: !include includes/input_datetimes.yaml
input_select: !include includes/input_selects.yaml
input_number: !include includes/input_numbers.yaml

# Logging and history
logger: !include includes/logger.yaml
recorder: !include includes/recorder.yaml

# Managed via UI
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Others
person: !include includes/persons.yaml
zone: !include includes/zones.yaml
group: !include includes/groups.yaml
automation old: !include_dir_merge_list automations
switch: !include includes/switches.yaml
sensor: !include includes/sensors.yaml
binary_sensor: !include includes/binary_sensors.yaml
# shell_command: !include includes/shell_commands.yaml
notify: !include includes/notify.yaml
light: !include includes/lights.yaml
wake_on_lan:
timer: !include includes/timers.yaml
ios: !include includes/ios.yaml
homekit: !include includes/homekit.yaml
influxdb: !include includes/influxdb.yaml
intent:
# intent_script: !include includes/intent_script.yaml
spotcast: !include includes/spotcast.yaml

# Custom components
pyscript: !include includes/pyscript.yaml
