- alias: "Climate: turn on the heating 30 min before waking up"
  triggers:
    trigger: template
    value_template: >
      {{ states("sensor.time")[0:5] == states("sensor.half_hour_before_alarm") }}
  conditions:
    condition: state
    entity_id:
      - input_boolean.alarm_clock
      - input_boolean.automatic_temperature
    state: "on"
  actions:
    action: script.set_high_temperature

- alias: "Climate: turn on the heating when going home"
  triggers:
    trigger: numeric_state
    entity_id: sensor.home_nearest_distance
    below: 6
    above: 1
  conditions:
    - condition: state
      entity_id: input_boolean.automatic_temperature
      state: "on"
    - condition: time
      after: "16:00:00"
      before: "22:00:00"
    - "{{ is_state('sensor.home_nearest_direction_of_travel', 'towards') }}"
    - "{{ not is_state_attr('climate.thermostat', 'temperature', states('input_number.temperature_high')) }}"
    - condition: state
      entity_id: binary_sensor.no_one_home
      state: "on"
  actions:
    - action: script.set_high_temperature
    - action: notify.all_iphones
      data:
        title: "Climate"
        message: "Automatically turned on the heating 🥵℃"

- alias: "Climate: turn off the heating at 22:00"
  triggers:
    trigger: time
    at: "22:00"
  conditions:
    - condition: state
      entity_id: input_boolean.automatic_temperature
      state: "on"
    - condition: state
      entity_id: binary_sensor.no_one_home
      state: "off"
    - "{{ not is_state_attr('climate.thermostat', 'temperature', states('input_number.temperature_low')|float(0)) }}"
  actions:
    - action: script.set_low_temperature
    - action: notify.all_iphones
      data:
        message: "Turned off the heating 🥶, click to turn it on again?"
        data:
          actions:
            - action: TURN_ON_HEATING
              title: Turn on heating
              activationMode: background
              authenticationRequired: true
              destructive: true
    - wait_for_trigger:
        trigger: event
        event_type: mobile_app_notification_action
        event_data:
          action: TURN_ON_HEATING
      timeout: "00:00:20"
      continue_on_timeout: false
    - action: script.set_high_temperature
# - alias: "Climate: set outside temperature every hour"
#   triggers:
#     trigger: time_pattern
#     hours: "/1"
#   actions:
#     action: mqtt.publish
#     data:
#       topic: actions/otmonitor/outside
#       payload: >
#         {{ state_attr("weather.liberte", "temperature") }}

# - alias: "Climate: set temperature setpoint to 50 °C"
#   triggers:
#     trigger: time_pattern
#     hours: "/2"
#   actions:
#     action: mqtt.publish
#     data:
#       topic: actions/otmonitor/maxdhwsetpt
#       payload: "50"
