- alias: "Frontend: turn on dark mode"
  triggers:
    - trigger: time
      at: "20:00"
    - trigger: sun
      event: sunset
  conditions: "{{ is_state('input_boolean.dark_mode', 'off') }}"
  actions:
    entity_id: input_boolean.dark_mode
    action: input_boolean.turn_on

- alias: "Frontend: turn on light mode"
  triggers:
    - trigger: time
      at: "06:00"
    - trigger: sun
      event: sunrise
  conditions: "{{ is_state('input_boolean.dark_mode', 'on') }}"
  actions:
    entity_id: input_boolean.dark_mode
    action: input_boolean.turn_off

- alias: "Frontend: change theme"
  triggers:
    - trigger: state
      entity_id: input_select.theme
    - trigger: state
      entity_id: input_boolean.dark_mode
    # - trigger: state
    #   entity_id: input_boolean.theme_alternative
    - trigger: homeassistant
      event: start
  actions:
    action: frontend.set_theme
    data:
      name: >
        {% set which = "dark" if is_state("input_boolean.dark_mode", "on") else "light" -%}
        {% set name = states("input_select.theme") -%}
        # {% set suffix = "-alternative" if is_state("input_boolean.theme_alternative", "on") else "" -%}
        {% set suffix = "-alternative" if is_state("input_boolean.dark_mode", "off") else "" -%}
        ios-{{ which }}-mode-{{ name }}{{ suffix }}
