- alias: "Leaving: automatically turn off everything"
  initial_state: "on"
  triggers:
    - trigger: state
      entity_id: binary_sensor.someone_in_the_house_in_last_hour
      from: "on"
      to: "off"
      for: "00:01:00"
    - trigger: time_pattern
      hours: "/1"
  conditions:
    - condition: state
      entity_id:
        - binary_sensor.no_one_home
        - binary_sensor.anything_on
      state: "on"
    - condition: state
      entity_id:
        - binary_sensor.someone_in_the_house_in_last_hour
      state: "off"
  actions:
    - action: script.leaving
    - action: notify.all_phones
      data:
        title: "Leaving"
        message: "Everything automatically turned off!"

- alias: "Leaving: ask to turn off everything"
  initial_state: "on"
  triggers:
    - trigger: state
      entity_id: person.fouppy
      from: "home"
    - trigger: state
      entity_id: person.moom
      from: "home"
  conditions:
    - condition: state
      entity_id:
        - binary_sensor.no_one_home
        - binary_sensor.anything_on
      state: "on"
  actions:
    - delay: "00:05:00" # something still needs to be on in 5 min
    - condition: state
      entity_id: binary_sensor.no_one_home
      state: "on"
    - action: notify.all_phones
      data:
        message: "No one is home, turn off everything?"
        data:
          actions:
            - action: TURN_OFF_EVERYTHING
              title: Turn off everything
              activationMode: background
              authenticationRequired: false
              destructive: true

- alias: "Leaving: turn off everything after notification"
  triggers:
    trigger: event
    event_type: mobile_app_notification_action
    event_data:
      action: TURN_OFF_EVERYTHING
  actions:
    action: script.leaving
