- alias: "Media player: update Spotify entity when TV is on every 5 seconds"
  triggers:
    trigger: time_pattern
    seconds: "/5"
  conditions:
    - condition: state
      entity_id: media_player.spotify_fouppy
      state: playing
    - condition: state
      entity_id: media_player.chromecast_2
      state: "on"
  actions:
    action: homeassistant.update_entity
    entity_id: media_player.spotify_fouppy
