- alias: "Music: start playlist"
  initial_state: "on"
  triggers:
    trigger: state
    entity_id: input_boolean.start_the_music
    from: "off"
    to: "on"
  actions:
    - action: input_boolean.turn_off
      entity_id: input_boolean.start_the_music
    - action: script.start_spotify_playlist_of_nearest_person
      data:
        source: KEF LS50
        entity_id: media_player.kef_ls50
