- alias: "Sleep mode: automatically turn off when alarm turns off or at 7AM"
  triggers:
    - trigger: time
      at: "07:00"
    - trigger: state
      entity_id: input_boolean.alarm_clock
      from: "on"
      to: "off"
  conditions:
    condition: state
    entity_id: input_boolean.alarm_clock
    state: "off"
  actions:
    entity_id: input_select.sleep_mode
    action: input_select.select_option
    data:
      option: "half"

- alias: "Sleep mode: set low temperature when sleep mode turns on"
  triggers:
    trigger: state
    entity_id: input_select.sleep_mode
    from: "off"
  actions:
    action: script.set_low_temperature

- alias: "Sleep mode: go from half to total sleeping mode"
  description: >
    When it is half sleeping mode and there is no activity in
    the house for more than an hour go to total sleeping mode.
  triggers:
    trigger: state
    entity_id: binary_sensor.activity_outside_bedroom
    to: "off"
    for: "01:00:00"
  conditions:
    condition: state
    entity_id: input_select.sleep_mode
    state: half
  actions:
    - action: input_select.select_option
      entity_id: input_select.sleep_mode
      data:
        option: "total"
    - action: notify.phone_fouppy
      data:
        title: "Sleep mode"
        message: "Automatically switched from 'half' to 'total' sleeping mode! 💤🛌"

- alias: "Sleep mode: set sleeping mode in the living room"
  description: >
    Set the living room lights to sleep mode only when no-one is there anymore.
  triggers:
    trigger: state
    entity_id: input_select.sleep_mode
    to: "total"
  actions:
    choose:
      - conditions: "{{ is_state('binary_sensor.activity_in_living_room', 'on') }}"
        sequence:
          - wait_for_trigger:
              trigger: state
              entity_id: binary_sensor.activity_in_living_room
              from: "on"
              to: "off"
            timeout: "06:00:00"
            continue_on_timeout: false
          - condition: state # make sure sleep mode is still on
            entity_id: input_select.sleep_mode
            state: "total"
