- alias: "Test: time"
  triggers:
    trigger: state
    entity_id: sensor.time
  actions:
    - variables:
        t_start: "{{ as_timestamp(now()) }}"
    - action: system_log.write
      data:
        message: "took {{ as_timestamp(now()) - t_start | int }}"
        level: debug
        logger: yolo.yolo
