- alias: "Utilities: washing machine or dishwasher started or finished"
  triggers:
    - trigger: state
      entity_id: binary_sensor.dishwasher
    - trigger: state
      entity_id: binary_sensor.washing_machine
  variables:
    from_state: "{{ trigger.from_state.state }}"
    to_state: "{{ trigger.to_state.state }}"
    name: "{{ trigger.entity_id.split('.', 1)[1] }}"
  conditions: "{{ (to_state == 'on' and from_state == 'off') or (to_state == 'off' and from_state == 'on') }}"
  actions:
    action: input_datetime.set_datetime
    data:
      entity_id: "input_datetime.{{ name }}_{{ to_state }}"
      timestamp: "{{ now().timestamp() }}"

- alias: "Utilities: washing machine notification"
  triggers:
    trigger: state
    entity_id: binary_sensor.washing_machine
    from: "on"
    to: "off"
  actions:
    action: script.utility_notification
    data:
      name: "Washing machine"
      emojis: "👚👕"

- alias: "Utilities: dishwasher notification"
  triggers:
    trigger: state
    entity_id: binary_sensor.dishwasher
    from: "on"
    to: "off"
  actions:
    action: script.utility_notification
    data:
      name: "Dishwasher"
      emojis: "🍽🍳"

- alias: "Utilities: switch mosquito plug on"
  mode: single
  triggers:
    - trigger: time
      at: "20:00:00"
  actions:
    - action: switch.turn_on
      target:
        entity_id: switch.living_room_mosquito_plug

- alias: "Utilities: switch mosquito plug off"
  mode: single
  triggers:
    - trigger: time
      at: "08:00:00"
  actions:
    - action: switch.turn_off
      target:
        entity_id: switch.living_room_mosquito_plug
