- alias: "Work: MooM left work notification for Fouppy"
  triggers:
    trigger: state
    entity_id: person.moom
    from: "Work"
  conditions:
    condition: time
    after: "15:00:00"
    before: "22:00:00"
  actions:
    action: notify.phone_fouppy
    data:
      title: "Work"
      message: "MooM has left work! ♥️🎉"
