- alias: "Work: Fouppy left work notification for MooM"
  triggers:
    trigger: state
    entity_id: person.fouppy
    from: "Fouppy Work"
  conditions:
    condition: time
    after: "15:00:00"
    before: "22:00:00"
  actions:
    action: notify.phone_moom
    data:
      title: "Work"
      message: "Fouppy has left work! ♥️🎉"

- alias: "Work: MooM left work notification for Fouppy"
  triggers:
    trigger: state
    entity_id: person.moom
    from: "MooM Work"
  conditions:
    condition: time
    after: "15:00:00"
    before: "22:00:00"
  actions:
    action: notify.phone_fouppy
    data:
      title: "Work"
      message: "MooM has left work! ♥️🎉"
