- platform: group
  name: Living room lights
  entities:
    - light.living_room_main_light
    - light.living_room_tv_light
    - light.living_room_string_lights
    - light.living_room_red_lamp
    - light.living_room_red_lava_lamp
    - light.living_room_blue_lava_lamp

- platform: group
  name: Bedroom lights
  entities:
    - light.bedroom_main_lamp
    - light.bedroom_red_lamp
    - light.bedroom_string_lights

- platform: group
  name: Bathroom lights
  entities:
    - light.bathroom_main_lamp

- platform: group
  name: Kitchen lights
  entities:
    - light.kitchen_ceiling
    - light.kitchen_countertop
    - light.kitchen_sink

- platform: group
  name: Office lights
  entities:
    - light.office_main_lamp
    - light.office_bookcases
    - light.office_lamp

- platform: group
  name: Hall lights
  entities:
    - light.hall_ceiling
