- platform: group
  name: Living room lights
  entities:
    - light.living_room_string_lights
    - light.salon_lampe_principale_light
    - light.salon_lampe_rouge_light
    - light.salon_lampe_tv_light
    - light.salon_lava_lampe_rouge_light
    - light.salon_lava_lampe_bleue_light

- platform: group
  name: Bedroom lights
  entities:
    - light.chambre_lampe_principale_light
    - light.chambre_lampe_rouge_light
    - light.chambre_guirlande_light

- platform: group
  name: Kitchen lights
  entities:
    - light.cuisine_lampe_principale_light
    - light.cuisine_plans_de_travail
    - light.cuisine_evier

- platform: group
  name: Office lights
  entities:
    - light.bureau_lampe_light

- platform: group
  name: Hall lights
  entities:
    - light.couloir_lampe
