- platform: group
  name: all_iphones
  services:
    - service: mobile_app_basnijholt_iphone_10
    - service: mobile_app_basnijholt_iphone_13
    - service: mobile_app_marcella_iphone_se2
    - service: mobile_app_marcella_iphone_14_pro

- platform: group
  name: bas
  services:
    - service: mobile_app_basnijholt_iphone_10
    - service: mobile_app_basnijholt_iphone_13
    - service: chrome

- platform: group
  name: 1+8_fouppy
  services:
    - service: mobile_app_basnijholt_iphone_10
    - service: mobile_app_basnijholt_iphone_13

- platform: group
  name: all
  services:
    - service: mobile_app_basnijholt_iphone_10
    - service: mobile_app_basnijholt_iphone_13
    - service: mobile_app_basnijholt_macbook
    - service: mobile_app_marcella_iphone_se2
    - service: mobile_app_marcella_iphone_14_pro
    - service: tv
    - service: chrome
