- platform: template
  sensors:
    dishwasher_watts:
      value_template: >
        {{ states("sensor.dishwasher_power") | float("Unavailable") }}
      unit_of_measurement: Watt
      friendly_name: Dishwasher usage

    washing_machine_watts:
      value_template: >
        {{ states("sensor.washing_machine_power") | float("Unavailable") }}
      unit_of_measurement: Watt
      friendly_name: Washing machine usage

    count_automations:
      icon_template: mdi:autorenew
      value_template: "{{ states.automation | count }}"

    count_scripts:
      icon_template: mdi:script-text-outline
      value_template: "{{ states.script| count }}"

    count_device_trackers:
      icon_template: mdi:map-marker
      value_template: "{{ states.device_tracker | count }}"

    count_binary_sensors:
      icon_template: mdi:unfold-more-horizontal
      value_template: "{{ states.binary_sensor| count }}"

    count_sensors:
      icon_template: mdi:resistor
      value_template: "{{ states.sensor | count }}"

    count_switches:
      icon_template: mdi:light-switch
      value_template: "{{ states.switch | count }}"

    count_zones:
      icon_template: mdi:map-marker-radius
      value_template: "{{ states.zone | count }}"

    count_input_booleans:
      icon_template: mdi:toggle-switch
      value_template: "{{ states.input_boolean | count }}"

    count_input_numbers:
      icon_template: mdi:numeric
      value_template: "{{ states.input_number | count }}"

    count_input_texts:
      icon_template: mdi:alphabetical
      value_template: "{{ states.input_text | count }}"

    count_input_selects:
      icon_template: mdi:view-list
      value_template: "{{ states.input_select | count }}"

    count_input_datetimes:
      icon_template: mdi:calendar-clock
      value_template: "{{ states.input_datetime | count }}"

    favorite_playlist_of_nearest_person:
      value_template: >
        {% if is_state("sensor.home_nearest_device", "Fouppy") %}
        6rPTm9dYftKcFAfwyRqmDZ
        {% else %}
        6rPTm9dYftKcFAfwyRqmDZ
        {% endif %}

    tv_volume:
      value_template: >
        {{ state_attr("media_player.tv_samsung", "volume_level") * 100 }}
      unit_of_measurement: "%"

    timestamp_start_of_today:
      value_template: >
        {{ as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0)) }}
      unit_of_measurement: "s"

    time_at_work_prognosis:
      friendly_name: Time at work prognosis
      value_template: >
        {% set day = [now().weekday(), 4] | min %}
        {% set t_total = states("sensor.time_at_work_this_week")|float(0) %}
        {% set t_today = states("sensor.time_at_work_today")|float(0) %}
        {% set hours_per_day_including_today = t_total / (day + 1) %}
        {% set hours_per_day_excluding_today = (t_total - t_today ) / (day + 10**-16) %}
        {% set seven_oclock = as_timestamp(now().replace(hour=19).replace(minute=0).replace(second=0)) %}

        {% if t_today > hours_per_day_excluding_today
              or (not is_state("person.moom", "Work") and t_today > 0)
              or (as_timestamp(now()) > seven_oclock)
              or day == 0
              or now().weekday() > 4
              or 5 * hours_per_day_including_today > 40 %}
          {% set hours_per_day = hours_per_day_including_today %}
        {% else %}
          {% set hours_per_day = hours_per_day_excluding_today %}
        {% endif %}

        {{ (5 * hours_per_day)|round(2) }}
      unit_of_measurement: h

    n_days_last_month:
      value_template: >
        {% set start_of_month = now().replace(day=1) %}
        {% set start_of_last_month = start_of_month.replace(month=now().month-1) %}
        {{ ((start_of_month - start_of_last_month).total_seconds() / 86400) | round }}

    daily_energy:
      friendly_name: Daily Energy
      unit_of_measurement: kWh
      value_template: >
        {{ states("sensor.all_energy_daily")|float(0) }}

    monthly_energy:
      friendly_name: Monthly Energy
      unit_of_measurement: kWh
      value_template: >
        {{ states("sensor.all_energy_monthly")|float(0) }}

    monthly_energy_last_period:
      friendly_name: Monthly Energy (Last period)
      unit_of_measurement: kWh
      value_template: >
        {{ state_attr("sensor.monthly_energy", "last_period")|float(0) }}

    monthly_energy_cost_last_period:
      friendly_name: Monthly Energy Cost (Last period)
      unit_of_measurement: €
      value_template: >
        {{ state_attr("sensor.monthly_energy_cost", "last_period")|float(0) }}

    energy_price:
      friendly_name: Energy price
      unit_of_measurement: €/kWh
      value_template: >
        {{ 0.2016 }}

    daily_energy_cost:
      friendly_name: Daily Energy Cost
      unit_of_measurement: €
      value_template: >
        {{ (states("sensor.daily_energy")|float(0) * states("sensor.energy_price")|float(0)) | round(2) }}

    monthly_energy_cost:
      friendly_name: Monthly Energy Cost
      unit_of_measurement: €
      value_template: >
        {{ (states("sensor.monthly_energy")|float(0) * states("sensor.energy_price")|float(0)) | round(2) }}

    nearest_phone_notify:
      friendly_name: Nearest phone's notify service
      value_template: >
        {% if is_state("person.fouppy", "home") and is_state("person.moom", "home") %}
          notify.all_phones
        {% elif is_state("sensor.home_nearest_device", "Fouppy") %}
          notify.phone_fouppy
        {% else %}
          notify.mobile_app_cph2465
        {% endif %}

    half_hour_before_alarm:
      friendly_name: Half an hour before alarm
      value_template: >
        {% set t_alarm = state_attr("input_datetime.alarm_clock", "timestamp") | int %}
        {% set t_start = states("sensor.timestamp_start_of_today") | int %}
        {% set half_hour_before_alarm = t_alarm + t_start - 60 * 30 %}
        {{ half_hour_before_alarm | timestamp_custom("%H:%M", True) }}

    ten_minutes_before_alarm:
      friendly_name: Ten minutes before alarm
      value_template: >
        {% set t_alarm = state_attr("input_datetime.alarm_clock", "timestamp") | int %}
        {% set t_start = states("sensor.timestamp_start_of_today") | int %}
        {% set before_alarm = t_alarm + t_start - 60 * 10 %}
        {{ before_alarm | timestamp_custom("%H:%M", True) }}

    lights_on_total_hours:
      friendly_name: Lights on total hours
      unit_of_measurement: h
      value_template: >
        {{ states('sensor.hours_bedroom_lights_have_been_on_last_7_days')|float(0) * 3
            + states('sensor.hours_living_room_lights_have_been_on_last_7_days')|float(0) * 6
            + states('sensor.hours_office_lights_has_been_on_last_7_days')|float(0) * 1
            + states('sensor.hours_kitchen_lights_have_been_on_last_7_days')|float(0) * 3
            + states('sensor.hours_hall_lights_have_been_on_last_7_days')|float(0) * 1 }}

    lights_on_total_kwh:
      unit_of_measurement: h
      value_template: >
        {{ states('sensor.lights_on_total_hours')|float(0) * 5.4 / 1000 }}

    robot_vacuum_last_clean_duration:
      unit_of_measurement: s
      value_template: >
        {% set t_start = state_attr("input_datetime.vacuum_on", "timestamp") | int %}
        {% set t_off = state_attr("input_datetime.vacuum_off", "timestamp") | int %}
        {% set duration = t_off - t_start %}
        {{ duration }}

- platform: statistics
  name: Bathroom thermostat humidity stats
  entity_id: sensor.bathroom_thermostat_humidity
  sampling_size: 86400 # make sure all data points of the last 24hrs are included
  max_age: "24:00:00"
  state_characteristic: mean

- platform: derivative
  source: sensor.bathroom_thermostat_humidity
  name: Bathroom thermostat humidity derivative
  unit_time: min
  time_window: "00:10:00"

# XXX: not used
- platform: min_max
  name: Temperature mean
  type: mean
  entity_ids:
    - sensor.bathroom_thermostat_temperature
    - sensor.dyson_temperature

- platform: min_max
  name: CPU Temperature mean
  type: mean
  entity_ids:
    - sensor.proxmox_node_core_0_temperature
    - sensor.proxmox_node_core_1_temperature

- platform: time_date
  display_options:
    - date
    - time

- platform: history_stats
  name: Hours TV has been on last 7 days
  entity_id: media_player.chromecast_2
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times TV has been on last 7 days
  entity_id: media_player.chromecast_2
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours dishwasher has been on last 7 days
  entity_id: binary_sensor.dishwasher
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times dishwasher has been on last 7 days
  entity_id: binary_sensor.dishwasher
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours washing machine has been on last 7 days
  entity_id: binary_sensor.washing_machine
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times washing machine has been on last 7 days
  entity_id: binary_sensor.washing_machine
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours bedroom lights have been on last 7 days
  entity_id: light.bedroom_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours living room lights have been on last 7 days
  entity_id: light.living_room_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours kitchen lights have been on last 7 days
  entity_id: light.kitchen_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours office lights has been on last 7 days
  entity_id: light.office_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours hall lights have been on last 7 days
  entity_id: light.hall_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Time at work this week
  entity_id: person.moom
  state: Work
  type: time
  start: >
    {{ states("sensor.timestamp_start_of_today")|float(0) - now().weekday() * 86400 }}
  end: "{{ now() }}"

- platform: history_stats
  name: Time at work today
  entity_id: person.moom
  state: Work
  type: time
  start: >
    {{ states("sensor.timestamp_start_of_today")|float(0) - 0 * 86400 }}
  duration:
    hours: 24

- platform: history_stats
  name: Time at work on Monday
  entity_id: person.moom
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 0 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(0) - day * 86400}}

- platform: history_stats
  name: Time at work on Tuesday
  entity_id: person.moom
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 1 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(0) - day * 86400}}

- platform: history_stats
  name: Time at work on Wednessday
  entity_id: person.moom
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 2 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(0) - day * 86400}}

- platform: history_stats
  name: Time at work on Thursday
  entity_id: person.moom
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 3 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(0) - day * 86400}}

- platform: history_stats
  name: Time at work on Friday
  entity_id: person.moom
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 4 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(0) - day * 86400}}
