- platform: template
  switches:
    vacuum_mode:
      value_template: >
        # standby, smart, wall_follow, spiral, chargego
        {{ is_state_attr("vacuum.hoover", "cleaning_mode", "smart") or is_state_attr("vacuum.hoover", "cleaning_mode", "wall_follow") or is_state_attr("vacuum.hoover", "cleaning_mode", "spiral") }}
      turn_on:
        action: vacuum.start
        entity_id: vacuum.hoover
      turn_off:
        action: vacuum.return_to_base
        entity_id: vacuum.hoover
