- platform: template
  switches:
    vacuum_mode:
      value_template: >
        {{ is_state("vacuum.chambre_aspirateur", "cleaning")}}
      turn_on:
        action: vacuum.smart
        entity_id: vacuum.chambre_aspirateur
      turn_off:
        action: vacuum.return_to_dock
        entity_id: vacuum.chambre_aspirateur
