- platform: template
  switches:
    vacuum_mode:
      value_template: >
        {{ is_state("vacuum.valetudo_vacuum", "cleaning")}}
      turn_on:
        action: vacuum.start
        entity_id: vacuum.valetudo_vacuum
      turn_off:
        action: vacuum.return_to_base
        entity_id: vacuum.valetudo_vacuum
